#!/usr/bin/env python
"""
Fine-tune a MatGL model using prepared JSON data.

Usage:
    python train_matgl.py --train-data path/to/train.json --val-data path/to/val.json \
        --model CHGNet-MatPES-PBE-2025.2.10-2.7M-PES --epochs 10 --lr 1e-3 --output-dir ./fine_tuning
"""

import argparse
import json
import os
import sys
from pathlib import Path
import numpy as np
import logging

# Add project root to sys.path
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../"))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Set MATGL_BACKEND to DGL by default for better performance and TensorNet support
if "MATGL_BACKEND" not in os.environ:
    os.environ["MATGL_BACKEND"] = "DGL"

from src.utils.mlips.device_utils import get_best_device
import ase
import ase.io

# Setup logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(description="Fine-tune a MatGL model")
    parser.add_argument(
        "--config",
        help="Path to JSON configuration file generated by generate_matgl_config.py",
    )
    # Basic arguments
    parser.add_argument(
        "--train-data", help="Path to JSON file containing training data"
    )
    parser.add_argument(
        "--val-data", help="Path to JSON file containing validation data (optional)"
    )
    parser.add_argument(
        "--model",
        default="CHGNet-MatPES-PBE-2025.2.10-2.7M-PES",
        help="Base model name or path to a checkpoint",
    )
    parser.add_argument(
        "--device", default="auto", help="Device to use (auto, cuda, cpu)"
    )
    parser.add_argument(
        "--output-dir", default="./fine_tuning", help="Directory to save the results"
    )

    # Training parameters
    parser.add_argument(
        "--epochs", type=int, default=200, help="Number of training epochs"
    )
    parser.add_argument("--lr", type=float, default=1e-2, help="Learning rate")
    parser.add_argument("--batch-size", type=int, default=2, help="Batch size")

    # Advanced parameters
    parser.add_argument(
        "--freeze-backbone",
        action="store_true",
        help="Freeze model backbone and only train readout heads",
    )
    parser.add_argument(
        "--reinit-head", action="store_true", help="Re-initialize readout head weights"
    )
    parser.add_argument(
        "--energy-weight", type=float, default=1.0, help="Loss weight for energy"
    )
    parser.add_argument(
        "--force-weight", type=float, default=10.0, help="Loss weight for forces"
    )
    parser.add_argument(
        "--stress-weight",
        type=float,
        default=1.0,
        help="Loss weight for stress (if present)",
    )
    parser.add_argument(
        "--scheduler",
        default="ReduceLROnPlateau",
        choices=["CosineAnnealingLR", "ReduceLROnPlateau"],
        help="Learning rate scheduler",
    )
    parser.add_argument(
        "--patience", type=int, default=20, help="Early stopping patience (epochs)"
    )

    args = parser.parse_args()

    if args.config:
        logger.info(f"Loading configuration from {args.config}")
        with open(args.config, "r") as f:
            config = json.load(f)
        for key, value in config.items():
            if hasattr(args, key) and value is not None:
                setattr(args, key, value)

    if not args.train_data:
        parser.error("--train-data is required unless provided in --config")

    # Load data
    logger.info(f"Loading training data from {args.train_data}...")
    with open(args.train_data, "r") as f:
        train_data = json.load(f)

    val_data = None
    if args.val_data:
        logger.info(f"Loading validation data from {args.val_data}...")
        with open(args.val_data, "r") as f:
            val_data = json.load(f)

    output_dir = Path(args.output_dir).absolute()
    output_dir.mkdir(parents=True, exist_ok=True)

    # Configure training
    training_config = {
        "max_epochs": args.epochs,
        "learning_rate": args.lr,
        "batch_size": args.batch_size,
        "freeze_backbone": args.freeze_backbone,
        "reinit_head": args.reinit_head,
        "energy_weight": args.energy_weight,
        "force_weight": args.force_weight,
        "stress_weight": args.stress_weight,
        "scheduler": args.scheduler,
    }

    if args.patience:
        training_config["patience"] = args.patience

    # Load model
    device = get_best_device(args.device)
    logger.info(f"Loading MatGL model: {args.model} on {device}")

    import matgl

    pot = matgl.load_model(args.model)
    pot.to(device)

    # Convert dict structures to ASE Atoms
    from pymatgen.io.ase import AseAtomsAdaptor
    from pymatgen.core import Structure
    from ase import Atoms
    import io

    adaptor = AseAtomsAdaptor()

    def process_data(data_list):
        processed = []
        for item in data_list:
            struct_data = item.get("structure") or item.get("atoms")
            if struct_data is None:
                continue

            atoms = None
            if isinstance(struct_data, Atoms):
                atoms = struct_data
            elif isinstance(struct_data, dict):
                try:
                    atoms = adaptor.get_atoms(Structure.from_dict(struct_data))
                except Exception:
                    try:
                        atoms = Atoms(
                            symbols=struct_data.get("symbols"),
                            positions=struct_data.get("positions"),
                            cell=struct_data.get("cell"),
                            pbc=struct_data.get("pbc", [True, True, True]),
                        )
                    except Exception:
                        pass
            elif isinstance(struct_data, str):
                try:
                    atoms = ase.io.read(io.StringIO(struct_data), format="extxyz")
                except Exception:
                    pass

            if atoms is None:
                continue

            new_item = item.copy()
            new_item["structure"] = atoms
            processed.append(new_item)
        return processed

    logger.info("Processing training structures...")
    processed_train_data = process_data(train_data)

    processed_val_data = None
    if val_data:
        logger.info("Processing validation structures...")
        processed_val_data = process_data(val_data)

    # --- Fine-tune Logic ---
    logger.info("Starting fine-tuning...")

    # Imports
    try:
        from matgl.utils.training import PotentialLightningModule
        from matgl.graph.data import MGLDataLoader, MGLDataset, collate_fn_pes

        try:
            from matgl.graph.data import split_dataset
        except ImportError:
            from dgl.data.utils import split_dataset
        import lightning as pl
        from matgl.ext.pymatgen import Structure2Graph
    except ImportError as e:
        logger.debug(f"Primary MatGL training imports failed: {e}")
        try:
            # MatGL < 1.0 or specific versions might have it here
            from matgl.utils._training_dgl import PotentialLightningModule
            from matgl.graph.data import MGLDataLoader, MGLDataset, collate_fn_pes
            from dgl.data.utils import split_dataset
            import lightning as pl
            from matgl.ext.pymatgen import Structure2Graph
        except ImportError as e2:
            logger.error(f"MatGL training imports failed: {e2}")
            sys.exit(1)

    # Re-implement TrainingHistoryCallback
    class TrainingHistoryCallback(pl.Callback):
        """Callback to collect training history during fine-tuning."""

        def __init__(self, avg_atoms_train=1.0, avg_atoms_val=1.0):
            super().__init__()
            self.avg_atoms_train = avg_atoms_train
            self.avg_atoms_val = avg_atoms_val
            self.training_history = {
                "loss_train": [],
                "loss_val": [],
                "energy_mae_train": [],
                "energy_mae_val": [],
                "energy_rmse_train": [],
                "energy_rmse_val": [],
                "force_mae_train": [],
                "force_mae_val": [],
                "force_rmse_train": [],
                "force_rmse_val": [],
                "stress_mae_train": [],
                "stress_mae_val": [],
                "stress_rmse_train": [],
                "stress_rmse_val": [],
            }

        def on_train_epoch_end(self, trainer, pl_module):
            if trainer.sanity_checking:
                return
            metrics = trainer.callback_metrics

            def get_metric(specific_keys, fallback_keys=[]):
                for key in specific_keys + fallback_keys:
                    if key in metrics:
                        val = metrics[key]
                        return float(val.item()) if hasattr(val, "item") else float(val)
                return None

            loss = get_metric(["train_Total_Loss", "train_loss"], ["loss"])
            if loss is not None:
                self.training_history["loss_train"].append(loss)

            e_mae = get_metric(["train_Energy_MAE", "train_energy_mae"], ["energy_mae"])
            if e_mae is not None:
                self.training_history["energy_mae_train"].append(
                    (e_mae / self.avg_atoms_train) * 1000
                )
            e_rmse = get_metric(
                ["train_Energy_RMSE", "train_energy_rmse"], ["energy_rmse"]
            )
            if e_rmse is not None:
                self.training_history["energy_rmse_train"].append(
                    (e_rmse / self.avg_atoms_train) * 1000
                )

            f_mae = get_metric(["train_Force_MAE", "train_force_mae"], ["force_mae"])
            if f_mae is not None:
                self.training_history["force_mae_train"].append(f_mae * 1000)
            f_rmse = get_metric(
                ["train_Force_RMSE", "train_force_rmse"], ["force_rmse"]
            )
            if f_rmse is not None:
                self.training_history["force_rmse_train"].append(f_rmse * 1000)

            s_mae = get_metric(["train_Stress_MAE", "train_stress_mae"], ["stress_mae"])
            if s_mae is not None:
                import ase.units

                self.training_history["stress_mae_train"].append(
                    s_mae * ase.units.GPa * 1000
                )
            s_rmse = get_metric(
                ["train_Stress_RMSE", "train_stress_rmse"], ["stress_rmse"]
            )
            if s_rmse is not None:
                import ase.units

                self.training_history["stress_rmse_train"].append(
                    s_rmse * ase.units.GPa * 1000
                )

        def on_validation_epoch_end(self, trainer, pl_module):
            if trainer.sanity_checking:
                return
            metrics = trainer.callback_metrics

            def get_metric(keys):
                for key in keys:
                    if key in metrics:
                        val = metrics[key]
                        return float(val.item()) if hasattr(val, "item") else float(val)
                return None

            loss = get_metric(["val_Total_Loss", "val_loss", "loss"])
            if loss is not None:
                self.training_history["loss_val"].append(loss)

            e_mae = get_metric(["val_Energy_MAE", "val_energy_mae", "energy_mae"])
            if e_mae is not None:
                self.training_history["energy_mae_val"].append(
                    (e_mae / self.avg_atoms_val) * 1000
                )
            e_rmse = get_metric(["val_Energy_RMSE", "val_energy_rmse", "energy_rmse"])
            if e_rmse is not None:
                self.training_history["energy_rmse_val"].append(
                    (e_rmse / self.avg_atoms_val) * 1000
                )

            f_mae = get_metric(["val_Force_MAE", "val_force_mae", "force_mae"])
            if f_mae is not None:
                self.training_history["force_mae_val"].append(f_mae * 1000)
            f_rmse = get_metric(["val_Force_RMSE", "val_force_rmse", "force_rmse"])
            if f_rmse is not None:
                self.training_history["force_rmse_val"].append(f_rmse * 1000)

            s_mae = get_metric(["val_Stress_MAE", "val_stress_mae", "stress_mae"])
            if s_mae is not None:
                import ase.units

                self.training_history["stress_mae_val"].append(
                    s_mae * ase.units.GPa * 1000
                )
            s_rmse = get_metric(["val_Stress_RMSE", "val_stress_rmse", "stress_rmse"])
            if s_rmse is not None:
                import ase.units

                self.training_history["stress_rmse_val"].append(
                    s_rmse * ase.units.GPa * 1000
                )

    def _prepare_training_data(training_data):
        import ase.units
        from pymatgen.core import Structure
        from pymatgen.io.ase import AseAtomsAdaptor
        from ase import Atoms

        adaptor = AseAtomsAdaptor()

        atoms_list, energies, forces, stresses = [], [], [], []
        for d in training_data:
            atoms = d["structure"]
            if isinstance(atoms, dict):
                try:
                    struct = Structure.from_dict(atoms)
                    atoms = adaptor.get_atoms(struct)
                except Exception:
                    continue
            elif not isinstance(atoms, Atoms):
                continue

            atoms_list.append(atoms)
            energies.append(d.get("energy", 0.0))
            forces.append(d.get("forces", np.zeros((len(atoms), 3))))

            s = d.get("stress")
            if s is not None:
                s_gpa = np.array(s) / ase.units.GPa
                if s_gpa.shape == (6,):
                    s_3x3 = np.array(
                        [
                            [s_gpa[0], s_gpa[5], s_gpa[4]],
                            [s_gpa[5], s_gpa[1], s_gpa[3]],
                            [s_gpa[4], s_gpa[3], s_gpa[2]],
                        ]
                    )
                elif s_gpa.shape == (3, 3):
                    s_3x3 = s_gpa
                else:
                    s_3x3 = np.zeros((3, 3))
                stresses.append(s_3x3)
            else:
                stresses.append(np.zeros((3, 3)))

        return atoms_list, np.array(energies), forces, stresses

    # 1. Prepare Data
    train_atoms, train_energies, train_forces, train_stresses = _prepare_training_data(
        processed_train_data
    )

    avg_atoms_train = np.mean([len(a) for a in train_atoms]) if train_atoms else 1.0
    avg_atoms_val = avg_atoms_train  # Default fallback

    from pymatgen.io.ase import AseAtomsAdaptor

    adaptor = AseAtomsAdaptor()
    structures = [adaptor.get_structure(a) for a in train_atoms]

    element_types = pot.model.element_types

    # Strictly extract cutoffs without dangerous arbitrary defaults.
    cutoff = getattr(pot.model, "cutoff")

    if hasattr(pot.model, "threebody_cutoff"):
        threebody_cutoff = pot.model.threebody_cutoff
    elif hasattr(pot.model, "three_body_cutoff"):
        threebody_cutoff = pot.model.three_body_cutoff
    else:
        raise AttributeError(
            f"Model {pot.model.__class__.__name__} is missing a three-body cutoff attribute (checked 'threebody_cutoff' and 'three_body_cutoff')."
        )

    converter = Structure2Graph(element_types=element_types, cutoff=cutoff)

    def to_list(obj):
        return obj.tolist() if hasattr(obj, "tolist") else obj

    labels = {
        "energies": to_list(train_energies),
        "forces": [to_list(f) for f in train_forces],
        "stresses": [to_list(s) for s in train_stresses],
    }

    # Use persistent dataset directory to cache graphs
    train_data_dir = Path(args.train_data).parent
    dataset_dir = train_data_dir / f".mgl_cache_{Path(args.model).name}"
    dataset_dir.mkdir(parents=True, exist_ok=True)
    dataset_dir = str(dataset_dir)

    is_chgnet = "CHGNet" in args.model
    dataset = MGLDataset(
        structures=structures,
        converter=converter,
        labels=labels,
        threebody_cutoff=threebody_cutoff,
        include_line_graph=True,
        directed_line_graph=is_chgnet,
        save_dir=os.path.join(dataset_dir, "train"),
    )

    if processed_val_data:
        val_atoms, val_energies, val_forces, val_stresses = _prepare_training_data(
            processed_val_data
        )
        if val_atoms:
            avg_atoms_val = np.mean([len(a) for a in val_atoms])
        val_structures = [adaptor.get_structure(a) for a in val_atoms]
        val_dataset = MGLDataset(
            structures=val_structures,
            converter=converter,
            labels={
                "energies": to_list(val_energies),
                "forces": [to_list(f) for f in val_forces],
                "stresses": [to_list(s) for s in val_stresses],
            },
            threebody_cutoff=threebody_cutoff,
            include_line_graph=True,
            directed_line_graph=is_chgnet,
            save_dir=os.path.join(dataset_dir, "val"),
        )
        train_ds, val_ds = dataset, val_dataset
    else:
        if len(dataset) > 1:
            val_split = 0.1
            train_ds, val_ds = split_dataset(
                dataset, [1.0 - val_split, val_split], shuffle=True
            )
        else:
            train_ds, val_ds = dataset, None

    # Custom collate
    def move_to_device(obj, device):
        if isinstance(obj, torch.Tensor):
            return obj.to(device)
        if isinstance(obj, dict):
            return {k: move_to_device(v, device) for k, v in obj.items()}
        if isinstance(obj, list):
            return [move_to_device(v, device) for v in obj]
        if isinstance(obj, tuple):
            return tuple(move_to_device(v, device) for v in obj)
        if hasattr(obj, "to"):
            return obj.to(device)
        return obj

    def my_collate(batch):
        return move_to_device(collate_fn_pes(batch, include_line_graph=True), device)

    train_loader, val_loader = MGLDataLoader(
        train_data=train_ds,
        val_data=val_ds,
        collate_fn=my_collate,
        batch_size=training_config["batch_size"],
        num_workers=0,
    )

    # 2. Setup Training Module
    if training_config["freeze_backbone"]:
        for param in pot.model.parameters():
            param.requires_grad = False
        unfrozen_count = 0
        for name, module in pot.model.named_modules():
            if any(
                x in name.lower() for x in ["readout", "mlp_out", "final", "output"]
            ):
                for param in module.parameters():
                    param.requires_grad = True
                    unfrozen_count += 1
        logger.info(
            f"MatGL backbone frozen. Unfrozen {unfrozen_count} parameters in readout layers."
        )

    if training_config["reinit_head"]:
        reinit_count = 0
        for name, module in pot.model.named_modules():
            if any(
                x in name.lower() for x in ["readout", "mlp_out", "final", "output"]
            ):
                for pname, param in module.named_parameters():
                    if "weight" in pname:
                        torch.nn.init.xavier_uniform_(param)
                        reinit_count += 1
                    elif "bias" in pname:
                        torch.nn.init.zeros_(param)
                        reinit_count += 1
        logger.info(
            f"reinit_head=True: Re-initialized {reinit_count} readout parameters"
        )

    prop_offset = getattr(pot, "element_refs", None)
    if prop_offset and hasattr(prop_offset, "property_offset"):
        prop_offset = prop_offset.property_offset

    pre_data_std = float(pot.data_std) if hasattr(pot, "data_std") else 1.0
    pre_data_mean = float(pot.data_mean) if hasattr(pot, "data_mean") else 0.0

    lit_model = PotentialLightningModule(
        model=pot.model,
        element_refs=prop_offset,
        lr=training_config["learning_rate"],
        include_line_graph=True,
        energy_weight=training_config["energy_weight"],
        force_weight=training_config["force_weight"],
        stress_weight=training_config["stress_weight"],
        decay_steps=1000,
        decay_alpha=0.01,
        data_std=pre_data_std,
        data_mean=pre_data_mean,
    )

    if training_config["scheduler"] == "ReduceLROnPlateau":
        original_configure = lit_model.configure_optimizers

        def custom_configure_optimizers():
            optimizers, _ = original_configure()
            scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                optimizers[0], mode="min", factor=0.5, patience=10
            )
            return optimizers, [
                {
                    "scheduler": scheduler,
                    "monitor": "val_Total_Loss",
                    "interval": "epoch",
                }
            ]

        lit_model.configure_optimizers = custom_configure_optimizers
        # Disable MatGL's faulty implicit step to let Lightning natively handle scheduling
        lit_model.on_train_epoch_end = lambda *args, **kwargs: None

    # 3. Trainer
    avg_atoms_train = np.mean([len(a) for a in train_atoms]) if train_atoms else 1.0
    avg_atoms_val = (
        np.mean([len(a) for a in val_atoms])
        if (processed_val_data and val_atoms)
        else avg_atoms_train
    )

    history_callback = TrainingHistoryCallback(
        avg_atoms_train=avg_atoms_train, avg_atoms_val=avg_atoms_val
    )
    callbacks = [history_callback]

    if args.patience:
        from lightning.pytorch.callbacks import EarlyStopping

        early_stopping = EarlyStopping(
            monitor="val_Total_Loss",
            patience=args.patience,
            mode="min",
            verbose=True,
        )
        callbacks.append(early_stopping)

    trainer = pl.Trainer(
        max_epochs=training_config["max_epochs"],
        accelerator="gpu" if str(device).startswith("cuda") else "cpu",
        devices=1,
        callbacks=callbacks,
        enable_checkpointing=True,
        default_root_dir=output_dir,
        logger=False,
    )

    logger.info(
        f"Starting MatGL fine-tuning for {training_config['max_epochs']} epochs"
    )

    if processed_val_data and val_loader:
        logger.info("Evaluating initial zero-shot performance (Epoch 0)...")
        trainer.validate(lit_model, val_loader)
        # Pad train lists with None so they align with the initial validation step
        for key in history_callback.training_history:
            if "train" in key:
                history_callback.training_history[key].append(None)

    trainer.fit(lit_model, train_loader, val_loader)

    logger.info("Fine-tuning complete!")
    logger.info(f"Saving checkpoint to {output_dir}...")

    # Save the fine-tuned model as checkpoint matching MatGLWrapper load format
    torch.save(
        {
            "model_name": args.model,
            "element_types": element_types,
            "weights": lit_model.model.state_dict(),
            "data_std": getattr(pot, "data_std", 1.0),
            "data_mean": getattr(pot, "data_mean", 0.0),
        },
        str(output_dir / "fine_tuned_model.pth"),
    )

    logger.info("Executing artifact saving routines...")
    # Save numerical history to JSON
    json_path = output_dir / "training_history.json"
    with open(json_path, "w") as f:
        json.dump(history_callback.training_history, f, indent=2)

    plot_path = output_dir / "training_history.png"
    try:
        import sys

        sys.path.append(
            str(Path(__file__).resolve().parent.parent.parent.parent.parent)
        )
        from src.utils.mlips.plot_utils import plot_training_history

        plot_training_history(
            training_history=history_callback.training_history,
            save_path=str(plot_path),
            show=False,
        )
        logger.info(f"Training history plot saved to {plot_path}")
    except Exception as e:
        logger.warning(f"Failed to generate training history plot: {e}")

    # Save a configuration file for record keeping
    result = {
        "status": "success" if trainer.current_epoch > 0 else "failed",
        "epochs": trainer.current_epoch,
        "final_loss": history_callback.training_history["loss_train"][-1]
        if history_callback.training_history["loss_train"]
        else None,
    }

    config_record = {
        "model": args.model,
        "train_data": str(args.train_data),
        "val_data": str(args.val_data) if args.val_data else None,
        "training_config": training_config,
        "result": result,
    }

    with open(output_dir / "finetune_record.json", "w") as f:
        json.dump(config_record, f, indent=2)

    # Save input configs for reproducibility
    from src.utils.config_utils import save_skill_inputs

    save_skill_inputs(args, args.output_dir)


if __name__ == "__main__":
    main()
